apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sportsrevyen
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 1
  readiness:
    path: isready
    initialDelay: 1
  preStopHook:
    http:
      path: /stop
  replicas:
    min: 1
    max: 3
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 50m
      memory: 64Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        diskAutoresize: true
        tier: db-custom-1-3840
        databases:
          - name: sportsrevyen
            envVarPrefix: DATABASE
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-sportsrevyen-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
